export const projects = {

  "exclusive-ecom": {
    name: "Exclusive E-Commerce",
    year: "2025",
    image: "/projects/e-com.webp",
    link: "https://exclusive-e-com-rasil.vercel.app/",
    description: "This project is a fully responsive e-commerce platform built with React 19, showcasing a sleek UI and smooth user experience. Users can browse dynamic product pages, manage a shopping cart, and enjoy advanced filtering. A unique checkout animation enriches interactivity. I implemented responsive design, reusable components, and state management using Context API. The site supports multiple product categories and is deployed on Vercel. Overall, this modern e-commerce site combines performance, clean aesthetics, and animation to provide a seamless shopping experience across all screen sizes.",
    tech1: "React",
    tech2: "Tailwind",
    tech3: "Framer",
    tech4: "Vercel",
    keyFeature1: "Dynamic product pages rendered using React Router DOM.",
    keyFeature2: "Integrated search and filter across all categories.",
    keyFeature3: "Checkout button triggers animated truck loading.",
    keyFeature4: "State managed using React's Context API system.",
    challenge: "The main challenge was using Context API and setting up dynamic routing, as it was my first complex project. Initially, I didn’t know how to structure the logic, but after exploring documentation and experimenting, I was able to implement both features successfully and gained confidence in React architecture.",
    img1: "/gifsPort/e-commerce.gif",
    img2: "/mockups/ecom/laptop.webp",
    img3: "/mockups/ecom/Ipad.webp",
    img4: "/mockups/ecom/iPhone.webp",


  },
  "zarghab-real-estate": {
    name: "Real-Estate",
    year: "2025",
    image: "/projects/real.webp",
    link: "https://zarghab-real-estate.vercel.app/",
    description: "I built a real estate plot management system using Next.js and Tailwind CSS. This sleek, responsive web app replaces traditional, clunky tools by providing dynamic admin control, real-time updates, and PDF export functionality. It supports full CRUD without page reloads and role-based dashboards for better user experience. The smart filtering feature allows quick access to plots based on category or name. A simulated backend via MockAPI added realism. This project blends modern frontend tech with practical real estate workflows, showcasing how to create scalable tools for agencies, agents, or internal company use.",
    tech1: "Next.js",
    tech2: "React.js",
    tech3: "Tailwind CSS",
    tech4: "Framer-Motion",
    keyFeature1: "Role-based dashboards for admins and regular users.",
    keyFeature2: "CRUD operations with real-time updates using MockAPI.",
    keyFeature3: "Smart filters for instant plot search by name or type.",
    keyFeature4: "Client-side PDF export for bookings and receipts.",
    challenge: "This was my first project in Next.js, and I was new to SSR, ISR, and CSR concepts. Handling so many pages while learning these rendering methods was overwhelming. It was also my first time working with an API and implementing full CRUD operations, which made the experience very educational.",
    img1: "/gifsPort/real-estate.gif",
    img2: "/mockups/real-estate/laptop.webp",
    img3: "/mockups/real-estate/Ipad.webp",
    img4: "/mockups/real-estate/iPhone.webp",

  },
  "ezy-logistics": {
    name: "EZY Logistics",
    year: "2025",
    image: "/projects/EZY.webp",
    link: "https://fulfillezy.com/",
    description: "This project involved designing and developing a high-performance website for a 3PL logistics service offered by a company, where I work as a front-end developer. The goal was to create a visually impressive and highly interactive user experience to better reflect the modern capabilities of the company. To achieve this, I integrated an interactive 3D model using Three.js, which added depth and visual storytelling to the site. The website was optimized for speed and responsiveness, ensuring a smooth experience across all devices. By combining clean UI design with immersive visuals, the project successfully delivered a strong digital presence that appeals to both clients and partners.",
    tech1: "Next.js",
    tech2: "React.js",
    tech3: "Three.js",
    tech4: "Framer-Motion",
    keyFeature1: " Created immersive 3D visuals using powerful Three.js library.",
    keyFeature2: "Optimized entire website for speed, SEO, and responsiveness.",
    keyFeature3: "Designed modern UI reflecting brand's identity.",
    keyFeature4: "Added 3D ship model matching 3PL logistics service theme.",
    challenge: "This project was straightforward for me, with no significant challenges encountered. My prior experience with animations and performance optimization allowed me to implement smooth transitions and 3D interactions efficiently, even across different devices and screen sizes.",
    img1: "/gifsPort/ezy.gif",
    img2: "/mockups/ezzy/laptop.webp",
    img3: "/mockups/ezzy/Ipad.webp",
    img4: "/mockups/ezzy/iPhone.webp",

  },
  "book-slider": {
    name: "3D Book",
    year: "2025",
    image: "/projects/VR.webp",
    link: "https://virtual-reality-chi.vercel.app/",
    description: "This project involved creating a unique, interactive 3D book experience using Three.js and React Three Fiber. The main highlight was the realistic sliding animation and the personalized engraving of my name on both the front and back covers. It pushed me creatively and technically, forcing me to explore 3D concepts and animation workflows. The result was a smooth, immersive experience with clean UI and a touch of personality. This was a big leap from traditional 2D interfaces, reflecting my commitment to exploring new technologies and constantly leveling up as a developer through real-world challenges.",
    tech1: "Three.js",
    tech2: "React.js",
    tech3: "R3F",
    tech4: "Tailwind CSS",
    keyFeature1: "Built a fully interactive 3D book using Three.js and React Three Fiber framework.",
    keyFeature2: "Engraved my name onto the front and back covers for a personal touch.",
    keyFeature3: "Styled clean and responsive UI using Tailwind CSS with a modern layout approach.",
    keyFeature4: "Achieved smooth and realistic 3D page slider transitions for immersive user interaction.",
    challenge: "This was my first time working with 3D and React Three Fiber. Understanding camera angles, lighting, and mesh interactions was difficult at first. I spent hours watching tutorials and debugging Three.js quirks. It was challenging but incredibly rewarding to turn a 3D concept into something smooth, personalized, and fully interactive.",
    img1: "/gifsPort/book.gif",
    img2: "/mockups/3D-book/laptop.webp",
    img3: "/mockups/3D-book/Ipad.webp",
    img4: "/mockups/3D-book/iPhone.webp",

  },

  "soch-ai-chatbot": {
    name: "Soch AI Chatbot",
    year: "2025",
    image: "/mockups/soch/laptop.webp",
    link: "https://sochai.ai/",
    description: "Soch AI is an immersive landing page promoting a chatbot app similar to ChatGPT. Built with Three.js and Matter.js, it features dynamic 3D visuals and interactive physics-based animations where cards fall from the sky and scatter on impact. The layout emphasizes modern UI principles, responsive design, and playful interactivity. This project combines stunning visuals, practical performance, and real-time user engagement, encouraging downloads with an entertaining and highly creative interface that mimics real-world physics while delivering a futuristic digital experience. Every element was crafted with user behavior and experience in mind to maximize user retention and interactivity.",
    tech1: "Three.js",
    tech2: "React.js",
    tech3: "Matter.js",
    tech4: "Tailwind CSS",
    keyFeature1: "Interactive physics-based cards fall and scatter dynamically.",
    keyFeature2: "Three.js renders imported 3D models with precision.",
    keyFeature3: "Responsive UI optimized for desktop and mobile.",
    keyFeature4: "Landing page built to maximize user downloads.",
    challenge: "I faced a serious issue with capsule collisions. Despite trying many solutions, nothing worked. After posting on GitHub and StackOverflow, a senior engineer from San Francisco offered help. Together, we debugged and solved the physics problem, making the animations behave correctly. It taught me how to approach collaborative debugging and strengthened my problem-solving skills in real-world animation issues.",
    img1: "/gifsPort/soch ai.gif",
    img2: "/mockups/soch/laptop.webp",
    img3: "/mockups/soch/Ipad.webp",
    img4: "/mockups/soch/iPhone.webp",

  },

};
